apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-server-data
  labels: 
    app: todo-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server
  labels:
    app: todo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-server
  template:
    metadata:
      labels:
        app: todo-server
    spec:
      containers:
      - name: todo-server
        image: todo-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: data
          mountPath: /data
        env:
        - name: DATABASE_PATH
          value: /data/todos.db
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: todo-server-data
---
apiVersion: v1
kind: Service
metadata:
  name: todo-server-service
spec:
  selector:
    app: todo-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
